import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>BBCap Controle de APIs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Image
          src="/bb-logo.png"
          alt="Banco do Brasil"
          width={600}
          height={400}
        />

        <div className={styles.grid}>
          <Link href="/api-doc">
            <a className={styles.card}>
              <h2>Documentação &rarr;</h2>
              <p>
                Acessar documentação com simulações e padrões de retorno de
                dados.
              </p>
            </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://tecban.com.br"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" Tecban"}
        </a>
      </footer>
    </div>
  );
};

export default Home;
